export const actionTypes = {
    ADD_ITEM: "ADD_ITEM",
    TOGGLE_IMPORTANT: "TOGGLE_IMPORTANT",
    DELETE_ITEM: "DELETE_ITEM",
    TOGGLE_COMPLETE: "TOGGLE_COMPLETE",
    REMOVE_EXPIRY: "REMOVE_EXPIRY",
    UPDATE_EXPIRY: "UPDATE_EXPIRY",
    SUBMIT_TEXT_EDIT: "SUBMIT_TEXT_EDIT",
    UPDATE_ITEMS_PER_PAGE: "UPDATE_ITEMS_PER_PAGE",
    UPDATE_PAGE_NUMBER: "UPDATE_PAGE_NUMBER",
    DELETE_ALL_EXPIRED: "DELETE_ALL_EXPIRED",
    DELETE_COMPLETED_TODOS: "DELETE_COMPLETED_TODOS",
    SET_AUTO_DELETE_COMPLETED: "SET_AUTO_DELETE_COMPLETED"
};