export const actionTypes = {
    ADD_ITEM: "ADD_ITEM",
    TOGGLE_IMPORTANT: "TOGGLE_IMPORTANT",
    DELETE_ITEM: "DELETE_ITEM",
    TOGGLE_COMPLETE: "TOGGLE_COMPLETE",
    REMOVE_EXPIRY: "REMOVE_EXPIRY",
    UPDATE_EXPIRY: "UPDATE_EXPIRY"
};